### ISSUE TITLE
ESP32-S2 performance test

### ISSUE THREAD

**Issue by PTS93** [bitbank2/JPEGDEC#1]
Hey, awesome library!
I just ran a quick test of the perf example on the ESP32-S2 if you want to add that to your benchmark table.
As a suggestion, maybe make it a markdown table then it can be expanded in the future from other users via a PR :)
My results (@240Mhz):
```
full sized decode in 202974 us
half sized decode in 167798 us
quarter sized decode in 46320 us
eighth sized decode in 38632 us
```

**Comment by bitbank2** [comment]
Hi Timon,
Thanks for running the test. I have an ESP32-S2. I didn't add the ESP32-S2 to my table because it performs worse than the original ESP32, so I thought that wasn't worth highlighting. I'll add your numbers.  I'm not sure I want to keep a running tally. The table was just to give people a general idea of the performance they would see.

**Comment by PTS93** [comment]
The ESP32 is a dual core LX6, the S2 is a single core LX7. It is marketed as considerably slower thats why I found it interesting to see how much in this case :)
Fair enough if you don't want more results. I just felt some people might be looking specifically for image decoding performance (like me) and want some pointers as to which MCU to choose.

**Comment by bitbank2** [comment]
That's an interesting point about using the perf numbers to choose an MCU. I hadn't considered that.
