### ISSUE TITLE
Possible more JPEG_SCALE ?

### ISSUE THREAD

**Issue by G-Remo** [bitbank2/JPEGDEC#76]
Hello, 
Is it possible to have more scale option like 1/16 or 1/32

I use your library with esp32cam, it s faster to decode and resize on the fly

Thanks

**Comment by bitbank2** [comment]
The scaling options exist because of the nature of JPEG compression. It's based on a 8x8 Discrete Cosine Transform and it's relatively easy to derive 1/2, 1/4 and 1/8 versions of each DCT block as you decode. To do other scales wouldn't be any different than normal pixel scaling after you decode the image.
